baseURL = "https://sven.eisenschmidt.website/"

locale = "en-us"
title = "Sven Eisenschmidt - Personal Blog"
timeZone = "Europe/Berlin"

[params]
description = "Personal website of Sven Eisenschmidt, based in Leipzig, Germany."
siteHeading = "Sven Eisenschmidt"
author = "Sven Eisenschmidt"
keywords = "Sven Eisenschmidt, Leipzig, Germany, video games, music, cycling, travel, software development, photography"
jobTitle = "Chief Technology & Product Officer"
employer = "roadsurfer"
employerUrl = "https://roadsurfer.com"
githubUrl = "https://github.com/sveneisenschmidt"
linkedinUrl = "https://linkedin.com/in/sveneisenschmidt"
stravaUrl = "https://strava.com/athletes/sveneisenschmidt"
email = "sven.eisenschmidt@gmail.com"

[mediaTypes."text/htaccess"]
delimiter = ""

[outputFormats.htaccess]
mediaType = "text/htaccess"
baseName = ".htaccess"
isPlainText = true
notAlternative = true

[taxonomies]

[permalinks.page]
photos = "/:year-:month-:day-:contentbasename/"
trips = "/:year-:month-:day-:contentbasename/"
notes = "/:year-:month-:day-:contentbasename/"
essays = "/:year-:month-:day-:contentbasename/"

[outputFormats.searchmeta]
mediaType = "application/json"
baseName = "search-meta"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "RSS", "htaccess", "searchmeta"]
section = ["HTML"]

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
codeFences = true
noClasses = false
lineNos = false

[markup.goldmark.parser.attribute]
block = true
title = true

[caches.getresource]
maxAge = 0
